apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  namespace: my-namespace
  name: unrestricted
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
    - "*"
  hostIPC: false
  hostPID: false
  hostNetwork: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - NET_RAW
  
