apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: my-namespace
  name: part2-job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: part2-job
            image: nyuappsec/assign3-db:v0
            command: 
            - /bin/sh
            - -c
            - mysql --host=10.108.74.191 --port=3306 --user=root --password=thisisatestthing. GiftcardSiteDB -e "SELECT VARIABLE_NAME, VARIABLE_VALUE FROM performance_schema.global_variables where VARIABLE_NAME like 'default_password_lifetime';" -e "SELECT * FROM information_schema.SCHEMATA where SCHEMA_NAME not in ('mysql','information_schema', 'sys', 'performance_schema');"
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: login-secrets
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              value: GiftcardSiteDB
          restartPolicy: Never
