kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: my-namespace
  name: static-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /vol/static
